# Global PPM 設定ファイル
# このファイルを編集して、分析のパラメータを設定してください

# =============================================================================
# 1. 分析期間設定（最重要 - ユーザーが最も関心を持つ設定）
# =============================================================================
# 推計される結果の期間を設定してください
# この期間のデータを使用して分析が実行されます
analysis_period:
  # 開始期間（YYYYMM形式、例：201909）
  start: 201909
  # 終了期間（YYYYMM形式、例：202406）
  end: 202406

# =============================================================================
# 2. 出力設定（結果の保存先）
# =============================================================================
# 分析結果の保存先を設定してください
output:
  # 結果保存ディレクトリ
  directory: "/tmp/gppm_output"
  # ファイル名設定
  files:
    # 変分推論結果ファイル
    variational_result: "variational_inference_result.pkl"
    # CSV処理結果ファイル
    csv_processed: "csv_processed_result.pkl"
    # 統合結果ファイル（変分推論 + CSV処理）
    integrated: "integrated_analysis_result.pkl"

# =============================================================================
# 3. 変分推論設定（ベイズ分析の核心）
# =============================================================================
# 変分推論によるベイズ分析の設定
variational_inference:
  # 既存の変分推論結果ファイル（統合処理で使用）
  existing_result_path: "/home/tmiyahara/repos/Neumann-Notebook/tmiyahara/202505/stan_result_15_usd2.pkl"
  
  # 新しい変分推論を実行する場合の設定
  new_inference:
    # 推論エンジン
    engine: "cmdstanpy"  # cmdstanpy, pystan, numpyro
    # Stanモデルファイル（nullの場合はデフォルトモデル）
    model_file: null
    # サンプル数（事後分布からのサンプル数）
    samples: 2000
    # 最適化反復数（変分推論の最適化回数）
    optimization_iterations: 500000
    # 乱数シード（再現性のため）
    random_seed: 42
    # 収束を要求するか
    require_convergence: false

# =============================================================================
# 4. データ処理設定（技術的な設定）
# =============================================================================
# 通常は変更不要。パフォーマンス調整が必要な場合のみ変更してください
data_processing:
  # CSV処理の並列化設定
  parallel_workers: 4  # CPUコア数に応じて調整
  # メモリ制限（MB）
  memory_limit_mb: 2048
  # データ型（メモリ使用量を削減したい場合は'float32'に変更）
  data_type: "float64"

# =============================================================================
# 5. ログ設定
# =============================================================================
# ログレベルの設定
log_level: INFO  # DEBUG, INFO, WARNING, ERROR, CRITICAL

# =============================================================================
# 6. オプション設定
# =============================================================================
# オプションのデータファイルパス
# デフォルト値を使用する場合はnullのままにしてください
optional_data:
  mapping_file: null